### ISSUE TITLE
Cant see my published themes

### ISSUE THREAD

**Issue by kislikjeka** [labithiotis/zed-themes#125]
**Describe the bug**
Cant delete manually uploaded theme. When go to My Themes there is a moment when i see rows and after they replaced with "You no themes yet"

**To Reproduce**

1. Upload theme from json file
2. Publish
3. Go to My Themes

**Expected behavior**
I can see my themes and delete them

**Comment by labithiotis** [comment]
Can confirm the issue. It's so f'ing strange, the SSR has the data and sends down HTML, but when remix JS runs, it fetches loaderData which is empty.

Ofc it works perfectly fine locally, I think the auth headers are being mangled by CF workers/pages at some point. I have noticed inconsistent behaviour from the clerk auth button, sometimes showing me signed in and other times not.

I am not doing anything special or complex with auth/deploy to warrant this sort of issue :(

**Comment by labithiotis** [comment]
@kislikjeka It's fixed, turned out I had caching enabled for all loader requests 🤦🏻
