### ISSUE TITLE
Add Rust language pack preview.

### ISSUE THREAD

**Issue by Rhelvetican** [labithiotis/zed-themes#50]
As a Rust programmer trying to make a theme for myself, it's a tad bit frustrating that I can't directly preview the theme in Rust.

**Comment by labithiotis** [comment]
@Rhelvetican glad to add Rust, could you provide me with an example snippet of code that includes most aspects of rust?

**Comment by labithiotis** [comment]
@Rhelvetican Rust has been added to list :)

**Comment by Rhelvetican** [comment]
glad to hear it :)
