### ISSUE TITLE
Lost all the configuration while switch language

### ISSUE THREAD

**Issue by mardiros** [labithiotis/zed-themes#80]
**Describe the bug**

Switching lang TSX / Rust / C# is resetting all the config set

**To Reproduce**

1. Go to 'Using https://zed-themes.com/themes/new'
2. Fillout some variable in the settings on the left bar
3. Change the language in the menu

![image](https://github.com/user-attachments/assets/f6b8d5bb-5470-49be-8ea6-d9dddb56cdaa)

4. All the configuration is lost

**Expected behavior**

The colors should be preserved

**Comment by labithiotis** [comment]
@mardiros Thank you so much for taking the time to report this issue, a fix is now deployed 🙌🏻
