### ISSUE TITLE
Save the state of the theme in local storage

### ISSUE THREAD

**Issue by mardiros** [labithiotis/zed-themes#82]
**Is your feature request related to a problem? Please describe.**

It's really easy to lost the theme you are trying to build. Actually I did not succeed yet.
You may encountered bugs, or even a refresh of the page.

**Describe the solution you'd like**

I suggest that the state of the theme should be saved in the local storage of the browser every time a changes happen.

**Describe alternatives you've considered**

A load button of the theme may be added to restart from a current backup or an existing theme in order to make some adjustment.

**Additional context**

I am new to zeditor, and none of the light theme are displaying property rulers (known as wrap_guides in zeditor).
The dark theme display them (it's really light) but the light theme rulers are almost invisible.

**Comment by labithiotis** [comment]
@mardiros Thank you so much for taking the time to report this issue, a fix is now deployed 🙌🏻
